name: valgrind
on: [ push, pull_request ]

jobs:
  Valgrind:
    runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2
  - name: install valgrind
  run: |
    sudo apt update
    sudo apt install -y valgrind
  - name: Run Valgrind
  run: make valgrind
